#!/usr/bin/env python3
"""Statistics of the premise-break experiment (DB test postgres_premise_break), as LaTeX macros.

usage: premise-stats.py exp/2026-10-08-optimize/premise-report.json [--tex-out overleaf/gen]

The test seeds the store-sales, store-returns, return-rate and electronics-revenue definitions, runs one rule
optimization round (key-range revisions), and re-keys the dates of February 2002 so that only date-key contiguity, the
premise the key-range rewrite added, fails. Reported: how many definitions were optimized, how many answers the layer
served after the change and how many were wrong, how many the key-range SQL would have got wrong had the premise not
been maintained (and by how much), the maintenance time of the fallback, and the join-completeness case (orphan item
keys).
"""
import argparse
import json
import os
import re
import statistics

PERIOD_EN = {"2002-02": "February", "2002-Q1": "the first quarter", "2002-H1": "the first half-year", "2002": "the year",
             "2002-09": "September"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("report")
    ap.add_argument("--tex-out")
    a = ap.parse_args()
    d = json.load(open(a.report, encoding="utf-8"))
    assert d.get("status") == "passed", d.get("error")
    r = d["rekey"]
    defs = [x for x in r["definitions"] if x["optimized"]]
    stale_wrong, rel_err, wrong_periods = 0, [], set()
    for x in defs:
        for p in x["answers"]:
            s = p["key_range_unmaintained"]
            if s and not s["correct"]:
                stale_wrong += 1
                wrong_periods.add(p["period"])
                rel_err.append(100 * abs(float(s["value"]) - float(p["gold"])) / abs(float(p["gold"])))
    maint = [e for e in r["events"] if e["event"] == "maintenance" and e.get("outcome") == "reinstated"]
    wall = [e["wall_ms"] for e in maint]
    db_ms = [e["db"]["ms"] for e in maint]
    m5 = d["orphan_items"]["m5"]["reason"]
    m = re.search(r"从 ([0-9.]+)% 升至 ([0-9.]+)%", m5)
    status = d["status_change"]
    print(f"rows {d['rows']}, optimized {len(defs)} of {len(r['definitions'])}, sweep {d['sweep_s']:.1f} s")
    print(f"answers served {r['answers']}, wrong {r['served_wrong']}; key-range without the premise wrong {stale_wrong} "
          f"({sorted(wrong_periods)}), relative error {min(rel_err):.1f}-{max(rel_err):.1f}%")
    print(f"fallback maintenance wall ms {[round(x) for x in wall]}, db ms {[round(x) for x in db_ms]}")
    print(f"orphan item keys: {m5}")
    print(f"status change: {status.get('before')} -> {status.get('after')}, "
          f"{ {k: v['accepted'] for k, v in (status.get('references') or {}).items()} }")
    if not a.tex_out:
        return
    periods = [PERIOD_EN[p] for p in ["2002-02", "2002-Q1", "2002-H1", "2002", "2002-09"] if p in wrong_periods]
    macros = {
        "PbRows": f"{d['rows']:,}".replace(",", "{,}"),
        "PbDefs": len(defs),
        "PbPeriods": len(defs[0]["answers"]),
        "PbAnswers": r["answers"],
        "PbServedWrong": r["served_wrong"],
        "PbStaleWrong": stale_wrong,
        "PbStaleWrongPerDef": stale_wrong // len(defs),
        "PbStaleErrMin": f"{min(rel_err):.2f}",
        "PbStaleErrMax": f"{max(rel_err):.0f}",
        "PbFallbackMsMax": f"{max(wall):,.0f}".replace(",", "{,}"),
        "PbFallbackMsMean": f"{statistics.mean(wall):,.0f}".replace(",", "{,}"),
        "PbOrphanBase": m.group(1) if m else "--",
        "PbOrphanNow": m.group(2) if m else "--",
    }
    path = os.path.join(a.tex_out, "premise.tex")
    with open(path, "w", encoding="utf-8") as f:
        f.write("% generated by tools/premise-stats.py; do not edit\n")
        for name, v in macros.items():
            f.write(f"\\newcommand{{\\{name}}}{{{v}}}\n")
    print(f"wrote {path}; wrong periods: {periods}")


if __name__ == "__main__":
    main()
